version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: soa_db
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: adonis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
